# Generated by Django 5.0.7 on 2024-07-24 19:45

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='info',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Info'),
        ),
    ]
