# Generated by Django 5.0.7 on 2024-08-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_remove_tours_image2_remove_tours_image3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='tours',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tour', 'verbose_name_plural': 'Toures'},
        ),
        migrations.AlterField(
            model_name='tours',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='tours.category', verbose_name='Categoria'),
        ),
    ]
