# Generated by Django 5.0.7 on 2024-08-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_category_options_alter_tours_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='category',
            field=models.ManyToManyField(to='tours.category', verbose_name='Categoria'),
        ),
    ]
