# Generated by Django 5.0.7 on 2024-08-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_tours_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='category',
            field=models.ManyToManyField(related_name='get_tour', to='tours.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='image1',
            field=models.ImageField(default='null', upload_to='tours'),
        ),
    ]
