# Generated by Django 5.0.7 on 2024-08-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_alter_tours_category_alter_tours_image1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado el')),
            ],
            options={
                'verbose_name': 'No Incluye',
                'verbose_name_plural': 'No Incluyes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Include',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado el')),
            ],
            options={
                'verbose_name': 'Incluye',
                'verbose_name_plural': 'Incluyes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tours',
            name='image2',
            field=models.ImageField(default='null', upload_to='tours'),
        ),
        migrations.AddField(
            model_name='tours',
            name='image3',
            field=models.ImageField(default='null', upload_to='tours'),
        ),
        migrations.AddField(
            model_name='tours',
            name='image4',
            field=models.ImageField(default='null', upload_to='tours'),
        ),
        migrations.AddField(
            model_name='tours',
            name='noinclude',
            field=models.ManyToManyField(to='tours.exclude', verbose_name='No Incluye'),
        ),
        migrations.AddField(
            model_name='tours',
            name='include',
            field=models.ManyToManyField(to='tours.include', verbose_name='Incluye'),
        ),
    ]
