# Generated by Django 5.0.7 on 2024-08-12 01:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_exclude_include_tours_image2_tours_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='time_end',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Hora de regreso'),
        ),
        migrations.AddField(
            model_name='tours',
            name='time_start',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Hora de salida'),
        ),
    ]
