# Generated by Django 5.0.7 on 2024-08-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_tours_time_end_tours_time_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
