# Generated by Django 5.0.7 on 2024-08-16 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_tours_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tours',
            options={'ordering': ['order'], 'verbose_name': 'Tour', 'verbose_name_plural': 'Toures'},
        ),
    ]
