# Generated by Django 5.1.1 on 2024-09-05 16:19

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_alter_tours_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='info',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.CreateModel(
            name='Cena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('image1', models.ImageField(default='null', upload_to='tours')),
                ('image2', models.ImageField(default='null', upload_to='tours')),
                ('image3', models.ImageField(default='null', upload_to='tours')),
                ('image4', models.ImageField(default='null', upload_to='tours')),
                ('info', django_ckeditor_5.fields.CKEditor5Field()),
                ('time_start', models.TimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Hora de salida')),
                ('time_end', models.TimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Hora de regreso')),
                ('cash', models.IntegerField(default=0, verbose_name='Valor')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado el')),
                ('include', models.ManyToManyField(to='tours.include', verbose_name='Incluye')),
                ('noinclude', models.ManyToManyField(to='tours.exclude', verbose_name='No Incluye')),
            ],
            options={
                'verbose_name': 'Cena',
                'verbose_name_plural': 'Cenas',
                'ordering': ['order'],
            },
        ),
    ]
