# Generated by Django 4.2.2 on 2023-06-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Valor'),
        ),
    ]
