# Generated by Django 4.2.2 on 2023-08-31 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_total_alter_booking_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='air',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Aerolinea'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='nair',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='numero de vuelo'),
            preserve_default=False,
        ),
    ]
