# Generated by Django 5.0.7 on 2024-08-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_air_booking_nair'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='air',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='nair',
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Telefono'),
        ),
    ]
