# Generated by Django 5.1.1 on 2024-12-24 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_options_remove_booking_air_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkin',
            field=models.DateField(default=datetime.date(2024, 12, 24), verbose_name='Checkin'),
        ),
    ]
