# Generated by Django 5.1.1 on 2024-12-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin',
            field=models.DateField(default=0, verbose_name='Checkin'),
        ),
    ]
