# Generated by Django 5.0.7 on 2024-07-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfers',
            name='image1',
            field=models.ImageField(default='null', upload_to='Imagen1'),
        ),
        migrations.AddField(
            model_name='transfers',
            name='image2',
            field=models.ImageField(default='null', upload_to='Imagen2'),
        ),
        migrations.AddField(
            model_name='transfers',
            name='image3',
            field=models.ImageField(default='null', upload_to='Imagen3'),
        ),
        migrations.AddField(
            model_name='transfers',
            name='image4',
            field=models.ImageField(default='null', upload_to='Imagen4'),
        ),
        migrations.AddField(
            model_name='transfers',
            name='image5',
            field=models.ImageField(default='null', upload_to='Imagen5'),
        ),
        migrations.AddField(
            model_name='transfers',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
    ]
