# Generated by Django 5.0.7 on 2024-08-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_transfers_image1_transfers_image2_transfers_image3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfers',
            options={'verbose_name': 'Transporte', 'verbose_name_plural': 'Transportes'},
        ),
        migrations.AlterField(
            model_name='transfers',
            name='image',
            field=models.ImageField(default='null', upload_to='transfers'),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='image1',
            field=models.ImageField(default='null', upload_to='transfers'),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='image2',
            field=models.ImageField(default='null', upload_to='transfers'),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='image3',
            field=models.ImageField(default='null', upload_to='transfers'),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='image4',
            field=models.ImageField(default='null', upload_to='transfers'),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='image5',
            field=models.ImageField(default='null', upload_to='transfers'),
        ),
    ]
