# Generated by Django 5.1.1 on 2024-12-13 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_alter_transfers_options_alter_transfers_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfers',
            options={'ordering': ['order'], 'verbose_name': 'Transporte', 'verbose_name_plural': 'Transportes'},
        ),
    ]
